#
# Generated by Chef for qa2.vocvox.com.
# Local modifications will be overwritten.
#

worker_processes 2
working_directory =  File.dirname(File.dirname(File.absolute_path __FILE__))
working_directory(working_directory)
listen "#{working_directory}/tmp/sockets/unicorn.sock"
pidfile = "#{working_directory}/tmp/pids/unicorn.pid"
pid pidfile

timeout 60

stderr_path "log/unicorn.stderr.log"

stdout_path "log/unicorn.stdout.log"

preload_app true

before_fork do |server, worker|
  old_pid = "#{pidfile}.oldbin"
  if File.exists?(old_pid) and server.pid != old_pid
    begin
      Process.kill('QUIT', File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end

  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.connection.disconnect!
  end

end

after_fork do |server, worker|
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.establish_connection
  end

end
